apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: app-con  # Updated to match the container port name in the Deployment
  selector:
    app: app
  type: LoadBalancer

