apiVersion: apps/v1
kind: Deployment
metadata:
  name: prormq
  labels:
    app: prormq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prormq
  template:
    metadata:
      labels:
        app: prormq
    spec:
      containers:
      - name: prormq
        image: rabbitmq
        ports:
        - containerPort: 15672
          name: prormq-port

        env:
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
               secretKeyRef:
                 name: app-secret
                 key: rmq-pass
          - name: RABBITMQ_DEFAULT_USER
            value: "guest"
